[package]
name = "react-native-wgpu"
version = "0.1.0"
edition = "2021"

[dependencies]
bytemuck = { version = "1.21.0", features = ["derive"] }
deno_core = "0.340.0"
pollster = { version =  "0.4.0" }
tokio = { version = "1.43.0", features = ["full"] }
wgpu = { version =  "24.0.1" }
winit = { version =  "0.30.9" }
