[package]
name = "react-native-wgpu"
version = "0.1.0"
edition = "2021"

[dependencies]
bytemuck = { version = "1.21.0", features = ["derive"] }
deno_core = "0.340.0"
deno_error = "0.5.6"
deno_fs = "0.105.0"
deno_resolver = "0.26.0"
deno_runtime = { version = "0.203.0", features = ["transpile"]}
pollster = { version =  "0.4.0" }
serde = { version = "1.0.218", features = ["derive"] }
sys_traits = "0.1.8"
tokio = { version = "1.43.0", features = ["full"] }
wgpu = { version =  "24.0.1" }
winit = { version =  "0.30.9" }
