export type TaffyDefaults = typeof TAFFY_STYLE_DEFAULTS;

export const TAFFY_STYLE_DEFAULTS = {
  display: "Flex",
  item_is_table: false,
  box_sizing: "BorderBox",
  overflow: { x: "Visible", y: "Visible" },
  scrollbar_width: 0,
  position: "Relative",
  inset: {
    left: "Auto",
    right: "Auto",
    top: "Auto",
    bottom: "Auto",
  },
  size: { width: "Auto", height: "Auto" },
  min_size: { width: "Auto", height: "Auto" },
  max_size: { width: "Auto", height: "Auto" },
  aspect_ratio: null,
  margin: {
    left: { Length: 0 },
    right: { Length: 0 },
    top: { Length: 0 },
    bottom: { Length: 0 },
  },
  padding: {
    left: { Length: 0 },
    right: { Length: 0 },
    top: { Length: 0 },
    bottom: { Length: 0 },
  },
  border: {
    left: { Length: 0 },
    right: { Length: 0 },
    top: { Length: 0 },
    bottom: { Length: 0 },
  },
  align_items: null,
  align_self: null,
  justify_items: null,
  justify_self: null,
  align_content: null,
  justify_content: null,
  gap: {
    width: { Length: 0 },
    height: { Length: 0 },
  },
  text_align: "Auto",
  flex_direction: "Row",
  flex_wrap: "NoWrap",
  flex_basis: "Auto",
  flex_grow: 0,
  flex_shrink: 1,
  grid_template_rows: [],
  grid_template_columns: [],
  grid_auto_rows: [],
  grid_auto_columns: [],
  grid_auto_flow: "Row",
  grid_row: { start: "Auto", end: "Auto" },
  grid_column: { start: "Auto", end: "Auto" },
} as const;
